[package]
name = "rueparse"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4"
byteorder = "1.5"
libloading = "0.8"
brotli = "8.0.0"
zstd = "0.13.3"
once_cell = "1.21.3"
oodle = { git = "https://github.com/sehnryr/oodle-rs.git", version = "0.1.0" }
