#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]

use super::EUnrealEngineObjectUE4Version;
use super::EUnrealEngineObjectUE5Version;
use super::FPackageFileVersion;

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EGame {
    UE4_0 = Self::GAME_UE4_0,
    UE4_1 = Self::GAME_UE4_1,
    UE4_2 = Self::GAME_UE4_2,
    UE4_3 = Self::GAME_UE4_3,
    UE4_4 = Self::GAME_UE4_4,
    UE4_5 = Self::GAME_UE4_5,
    ArkSurvivalEvolved = Self::GAME_ArkSurvivalEvolved,
    UE4_6 = Self::GAME_UE4_6,
    UE4_7 = Self::GAME_UE4_7,
    UE4_8 = Self::GAME_UE4_8,
    UE4_9 = Self::GAME_UE4_9,
    UE4_10 = Self::GAME_UE4_10,
    SeaOfThieves = Self::GAME_SeaOfThieves,
    UE4_11 = Self::GAME_UE4_11,
    GearsOfWar4 = Self::GAME_GearsOfWar4,
    DaysGone = Self::GAME_DaysGone,
    UE4_12 = Self::GAME_UE4_12,
    UE4_13 = Self::GAME_UE4_13,
    StateOfDecay2 = Self::GAME_StateOfDecay2,
    UE4_14 = Self::GAME_UE4_14,
    TEKKEN7 = Self::GAME_TEKKEN7,
    UE4_15 = Self::GAME_UE4_15,
    UE4_16 = Self::GAME_UE4_16,
    PlayerUnknownsBattlegrounds = Self::GAME_PlayerUnknownsBattlegrounds,
    TrainSimWorld2020 = Self::GAME_TrainSimWorld2020,
    UE4_17 = Self::GAME_UE4_17,
    AWayOut = Self::GAME_AWayOut,
    UE4_18 = Self::GAME_UE4_18,
    KingdomHearts3 = Self::GAME_KingdomHearts3,
    FinalFantasy7Remake = Self::GAME_FinalFantasy7Remake,
    AceCombat7 = Self::GAME_AceCombat7,
    FridayThe13th = Self::GAME_FridayThe13th,
    GameForPeace = Self::GAME_GameForPeace,
    UE4_19 = Self::GAME_UE4_19,
    Paragon = Self::GAME_Paragon,
    UE4_20 = Self::GAME_UE4_20,
    Borderlands3 = Self::GAME_Borderlands3,
    UE4_21 = Self::GAME_UE4_21,
    StarWarsJediFallenOrder = Self::GAME_StarWarsJediFallenOrder,
    Undawn = Self::GAME_Undawn,
    UE4_22 = Self::GAME_UE4_22,
    UE4_23 = Self::GAME_UE4_23,
    ApexLegendsMobile = Self::GAME_ApexLegendsMobile,
    UE4_24 = Self::GAME_UE4_24,
    TonyHawkProSkater12 = Self::GAME_TonyHawkProSkater12,
    BigRumbleBoxingCreedChampions = Self::GAME_BigRumbleBoxingCreedChampions,
    UE4_25 = Self::GAME_UE4_25,
    UE4_25_Plus = Self::GAME_UE4_25_Plus,
    RogueCompany = Self::GAME_RogueCompany,
    DeadIsland2 = Self::GAME_DeadIsland2,
    KenaBridgeofSpirits = Self::GAME_KenaBridgeofSpirits,
    Strinova = Self::GAME_Strinova,
    SYNCED = Self::GAME_SYNCED,
    OperationApocalypse = Self::GAME_OperationApocalypse,
    Farlight84 = Self::GAME_Farlight84,
    StarWarsHunters = Self::GAME_StarWarsHunters,
    ThePathless = Self::GAME_ThePathless,
    UE4_26 = Self::GAME_UE4_26,
    GTATheTrilogyDefinitiveEdition = Self::GAME_GTATheTrilogyDefinitiveEdition,
    ReadyOrNot = Self::GAME_ReadyOrNot,
    BladeAndSoul = Self::GAME_BladeAndSoul,
    TowerOfFantasy = Self::GAME_TowerOfFantasy,
    FinalFantasy7Rebirth = Self::GAME_FinalFantasy7Rebirth,
    TheDivisionResurgence = Self::GAME_TheDivisionResurgence,
    StarWarsJediSurvivor = Self::GAME_StarWarsJediSurvivor,
    Snowbreak = Self::GAME_Snowbreak,
    TorchlightInfinite = Self::GAME_TorchlightInfinite,
    QQ = Self::GAME_QQ,
    WutheringWaves = Self::GAME_WutheringWaves,
    DreamStar = Self::GAME_DreamStar,
    MidnightSuns = Self::GAME_MidnightSuns,
    FragPunk = Self::GAME_FragPunk,
    RacingMaster = Self::GAME_RacingMaster,
    UE4_27 = Self::GAME_UE4_27,
    Splitgate = Self::GAME_Splitgate,
    HYENAS = Self::GAME_HYENAS,
    HogwartsLegacy = Self::GAME_HogwartsLegacy,
    OutlastTrials = Self::GAME_OutlastTrials,
    Valorant = Self::GAME_Valorant,
    Gollum = Self::GAME_Gollum,
    Grounded = Self::GAME_Grounded,
    DeltaForceHawkOps = Self::GAME_DeltaForceHawkOps,
    MortalKombat1 = Self::GAME_MortalKombat1,
    VisionsofMana = Self::GAME_VisionsofMana,
    Spectre = Self::GAME_Spectre,
    KartRiderDrift = Self::GAME_KartRiderDrift,
    ThroneAndLiberty = Self::GAME_ThroneAndLiberty,
    MotoGP24 = Self::GAME_MotoGP24,
    Stray = Self::GAME_Stray,
    CrystalOfAtlan = Self::GAME_CrystalOfAtlan,
    PromiseMascotAgency = Self::GAME_PromiseMascotAgency,
    UE4_28 = Self::GAME_UE4_28,
    UE5_0 = Self::GAME_UE5_0,
    MeetYourMaker = Self::GAME_MeetYourMaker,
    BlackMythWukong = Self::GAME_BlackMythWukong,
    UE5_1 = Self::GAME_UE5_1,
    ThreeOnThreeFreeStyleRebound = Self::GAME_3on3FreeStyleRebound,
    Stalker2 = Self::GAME_Stalker2,
    TheCastingofFrankStone = Self::GAME_TheCastingofFrankStone,
    SilentHill2Remake = Self::GAME_SilentHill2Remake,
    UE5_2 = Self::GAME_UE5_2,
    DeadByDaylight = Self::GAME_DeadByDaylight,
    PaxDei = Self::GAME_PaxDei,
    TheFirstDescendant = Self::GAME_TheFirstDescendant,
    MetroAwakening = Self::GAME_MetroAwakening,
    ARKSurvivalAscended = Self::GAME_ARKSurvivalAscended,
    UE5_3 = Self::GAME_UE5_3,
    MarvelRivals = Self::GAME_MarvelRivals,
    Placeholder = Self::GAME_Placeholder,
    NobodyWantsToDie = Self::GAME_NobodyWantsToDie,
    MonsterJamShowdown = Self::GAME_MonsterJamShowdown,
    Rennsport = Self::GAME_Rennsport,
    AshesOfCreation = Self::GAME_AshesOfCreation,
    Avowed = Self::GAME_Avowed,
    UE5_4 = Self::GAME_UE5_4,
    FunkoFusion = Self::GAME_FunkoFusion,
    InfinityNikki = Self::GAME_InfinityNikki,
    NevernessToEverness = Self::GAME_NevernessToEverness,
    Gothic1Remake = Self::GAME_Gothic1Remake,
    SplitFiction = Self::GAME_SplitFiction,
    WildAssault = Self::GAME_WildAssault,
    InZOI = Self::GAME_InZOI,
    TempestRising = Self::GAME_TempestRising,
    UE5_5 = Self::GAME_UE5_5,
    Brickadia = Self::GAME_Brickadia,
    Splitgate2 = Self::GAME_Splitgate2,
    DeadzoneRogue = Self::GAME_DeadzoneRogue,
    MotoGP25 = Self::GAME_MotoGP25,
    UE5_6 = Self::GAME_UE5_6,
    UE5_7 = Self::GAME_UE5_7,
}
impl EGame {
    pub const GAME_UE4_BASE: u32 = 0x04000000;
    pub const GAME_UE5_BASE: u32 = 0x05000000;

    pub const GAME_UE4_0: u32 = Self::GAME_UE4_BASE + (0 << 16);
    pub const GAME_UE4_1: u32 = Self::GAME_UE4_BASE + (1 << 16);
    pub const GAME_UE4_2: u32 = Self::GAME_UE4_BASE + (2 << 16);
    pub const GAME_UE4_3: u32 = Self::GAME_UE4_BASE + (3 << 16);
    pub const GAME_UE4_4: u32 = Self::GAME_UE4_BASE + (4 << 16);
    pub const GAME_UE4_5: u32 = Self::GAME_UE4_BASE + (5 << 16);
    pub const GAME_ArkSurvivalEvolved: u32 = Self::GAME_UE4_5 + 1;
    pub const GAME_UE4_6: u32 = Self::GAME_UE4_BASE + (6 << 16);
    pub const GAME_UE4_7: u32 = Self::GAME_UE4_BASE + (7 << 16);
    pub const GAME_UE4_8: u32 = Self::GAME_UE4_BASE + (8 << 16);
    pub const GAME_UE4_9: u32 = Self::GAME_UE4_BASE + (9 << 16);
    pub const GAME_UE4_10: u32 = Self::GAME_UE4_BASE + (10 << 16);
    pub const GAME_SeaOfThieves: u32 = Self::GAME_UE4_10 + 1;
    pub const GAME_UE4_11: u32 = Self::GAME_UE4_BASE + (11 << 16);
    pub const GAME_GearsOfWar4: u32 = Self::GAME_UE4_11 + 1;
    pub const GAME_DaysGone: u32 = Self::GAME_UE4_11 + 2;
    pub const GAME_UE4_12: u32 = Self::GAME_UE4_BASE + (12 << 16);
    pub const GAME_UE4_13: u32 = Self::GAME_UE4_BASE + (13 << 16);
    pub const GAME_StateOfDecay2: u32 = Self::GAME_UE4_13 + 1;
    pub const GAME_UE4_14: u32 = Self::GAME_UE4_BASE + (14 << 16);
    pub const GAME_TEKKEN7: u32 = Self::GAME_UE4_14 + 1;
    pub const GAME_UE4_15: u32 = Self::GAME_UE4_BASE + (15 << 16);
    pub const GAME_UE4_16: u32 = Self::GAME_UE4_BASE + (16 << 16);
    pub const GAME_PlayerUnknownsBattlegrounds: u32 = Self::GAME_UE4_16 + 1;
    pub const GAME_TrainSimWorld2020: u32 = Self::GAME_UE4_16 + 2;
    pub const GAME_UE4_17: u32 = Self::GAME_UE4_BASE + (17 << 16);
    pub const GAME_AWayOut: u32 = Self::GAME_UE4_17 + 1;
    pub const GAME_UE4_18: u32 = Self::GAME_UE4_BASE + (18 << 16);
    pub const GAME_KingdomHearts3: u32 = Self::GAME_UE4_18 + 1;
    pub const GAME_FinalFantasy7Remake: u32 = Self::GAME_UE4_18 + 2;
    pub const GAME_AceCombat7: u32 = Self::GAME_UE4_18 + 3;
    pub const GAME_FridayThe13th: u32 = Self::GAME_UE4_18 + 4;
    pub const GAME_GameForPeace: u32 = Self::GAME_UE4_18 + 5;
    pub const GAME_UE4_19: u32 = Self::GAME_UE4_BASE + (19 << 16);
    pub const GAME_Paragon: u32 = Self::GAME_UE4_19 + 1;
    pub const GAME_UE4_20: u32 = Self::GAME_UE4_BASE + (20 << 16);
    pub const GAME_Borderlands3: u32 = Self::GAME_UE4_20 + 1;
    pub const GAME_UE4_21: u32 = Self::GAME_UE4_BASE + (21 << 16);
    pub const GAME_StarWarsJediFallenOrder: u32 = Self::GAME_UE4_21 + 1;
    pub const GAME_Undawn: u32 = Self::GAME_UE4_21 + 2;
    pub const GAME_UE4_22: u32 = Self::GAME_UE4_BASE + (22 << 16);
    pub const GAME_UE4_23: u32 = Self::GAME_UE4_BASE + (23 << 16);
    pub const GAME_ApexLegendsMobile: u32 = Self::GAME_UE4_23 + 1;
    pub const GAME_UE4_24: u32 = Self::GAME_UE4_BASE + (24 << 16);
    pub const GAME_TonyHawkProSkater12: u32 = Self::GAME_UE4_24 + 1;
    pub const GAME_BigRumbleBoxingCreedChampions: u32 = Self::GAME_UE4_24 + 2;
    pub const GAME_UE4_25: u32 = Self::GAME_UE4_BASE + (25 << 16);
    pub const GAME_UE4_25_Plus: u32 = Self::GAME_UE4_25 + 1;
    pub const GAME_RogueCompany: u32 = Self::GAME_UE4_25 + 2;
    pub const GAME_DeadIsland2: u32 = Self::GAME_UE4_25 + 3;
    pub const GAME_KenaBridgeofSpirits: u32 = Self::GAME_UE4_25 + 4;
    pub const GAME_Strinova: u32 = Self::GAME_UE4_25 + 5;
    pub const GAME_SYNCED: u32 = Self::GAME_UE4_25 + 6;
    pub const GAME_OperationApocalypse: u32 = Self::GAME_UE4_25 + 7;
    pub const GAME_Farlight84: u32 = Self::GAME_UE4_25 + 8;
    pub const GAME_StarWarsHunters: u32 = Self::GAME_UE4_25 + 9;
    pub const GAME_ThePathless: u32 = Self::GAME_UE4_25 + 10;
    pub const GAME_UE4_26: u32 = Self::GAME_UE4_BASE + (26 << 16);
    pub const GAME_GTATheTrilogyDefinitiveEdition: u32 = Self::GAME_UE4_26 + 1;
    pub const GAME_ReadyOrNot: u32 = Self::GAME_UE4_26 + 2;
    pub const GAME_BladeAndSoul: u32 = Self::GAME_UE4_26 + 3;
    pub const GAME_TowerOfFantasy: u32 = Self::GAME_UE4_26 + 4;
    pub const GAME_FinalFantasy7Rebirth: u32 = Self::GAME_UE4_26 + 5;
    pub const GAME_TheDivisionResurgence: u32 = Self::GAME_UE4_26 + 6;
    pub const GAME_StarWarsJediSurvivor: u32 = Self::GAME_UE4_26 + 7;
    pub const GAME_Snowbreak: u32 = Self::GAME_UE4_26 + 8;
    pub const GAME_TorchlightInfinite: u32 = Self::GAME_UE4_26 + 9;
    pub const GAME_QQ: u32 = Self::GAME_UE4_26 + 10;
    pub const GAME_WutheringWaves: u32 = Self::GAME_UE4_26 + 11;
    pub const GAME_DreamStar: u32 = Self::GAME_UE4_26 + 12;
    pub const GAME_MidnightSuns: u32 = Self::GAME_UE4_26 + 13;
    pub const GAME_FragPunk: u32 = Self::GAME_UE4_26 + 14;
    pub const GAME_RacingMaster: u32 = Self::GAME_UE4_26 + 15;
    pub const GAME_UE4_27: u32 = Self::GAME_UE4_BASE + (27 << 16);
    pub const GAME_Splitgate: u32 = Self::GAME_UE4_27 + 1;
    pub const GAME_HYENAS: u32 = Self::GAME_UE4_27 + 2;
    pub const GAME_HogwartsLegacy: u32 = Self::GAME_UE4_27 + 3;
    pub const GAME_OutlastTrials: u32 = Self::GAME_UE4_27 + 4;
    pub const GAME_Valorant: u32 = Self::GAME_UE4_27 + 5;
    pub const GAME_Gollum: u32 = Self::GAME_UE4_27 + 6;
    pub const GAME_Grounded: u32 = Self::GAME_UE4_27 + 7;
    pub const GAME_DeltaForceHawkOps: u32 = Self::GAME_UE4_27 + 8;
    pub const GAME_MortalKombat1: u32 = Self::GAME_UE4_27 + 9;
    pub const GAME_VisionsofMana: u32 = Self::GAME_UE4_27 + 10;
    pub const GAME_Spectre: u32 = Self::GAME_UE4_27 + 11;
    pub const GAME_KartRiderDrift: u32 = Self::GAME_UE4_27 + 12;
    pub const GAME_ThroneAndLiberty: u32 = Self::GAME_UE4_27 + 13;
    pub const GAME_MotoGP24: u32 = Self::GAME_UE4_27 + 14;
    pub const GAME_Stray: u32 = Self::GAME_UE4_27 + 15;
    pub const GAME_CrystalOfAtlan: u32 = Self::GAME_UE4_27 + 16;
    pub const GAME_PromiseMascotAgency: u32 = Self::GAME_UE4_27 + 17;
    pub const GAME_UE4_28: u32 = Self::GAME_UE4_BASE + (28 << 16);

    pub const GAME_UE4_LATEST: EGame = Self::UE4_28;

    pub const GAME_UE5_0: u32 = Self::GAME_UE5_BASE + (0 << 16);
    pub const GAME_MeetYourMaker: u32 = Self::GAME_UE5_0 + 1;
    pub const GAME_BlackMythWukong: u32 = Self::GAME_UE5_0 + 2;
    pub const GAME_UE5_1: u32 = Self::GAME_UE5_BASE + (1 << 16);
    pub const GAME_3on3FreeStyleRebound: u32 = Self::GAME_UE5_1 + 1;
    pub const GAME_Stalker2: u32 = Self::GAME_UE5_1 + 2;
    pub const GAME_TheCastingofFrankStone: u32 = Self::GAME_UE5_1 + 3;
    pub const GAME_SilentHill2Remake: u32 = Self::GAME_UE5_1 + 4;
    pub const GAME_UE5_2: u32 = Self::GAME_UE5_BASE + (2 << 16);
    pub const GAME_DeadByDaylight: u32 = Self::GAME_UE5_2 + 1;
    pub const GAME_PaxDei: u32 = Self::GAME_UE5_2 + 2;
    pub const GAME_TheFirstDescendant: u32 = Self::GAME_UE5_2 + 3;
    pub const GAME_MetroAwakening: u32 = Self::GAME_UE5_2 + 4;
    pub const GAME_ARKSurvivalAscended: u32 = Self::GAME_UE5_2 + 5;
    pub const GAME_UE5_3: u32 = Self::GAME_UE5_BASE + (3 << 16);
    pub const GAME_MarvelRivals: u32 = Self::GAME_UE5_3 + 1;
    pub const GAME_Placeholder: u32 = Self::GAME_UE5_3 + 2;
    pub const GAME_NobodyWantsToDie: u32 = Self::GAME_UE5_3 + 3;
    pub const GAME_MonsterJamShowdown: u32 = Self::GAME_UE5_3 + 4;
    pub const GAME_Rennsport: u32 = Self::GAME_UE5_3 + 5;
    pub const GAME_AshesOfCreation: u32 = Self::GAME_UE5_3 + 6;
    pub const GAME_Avowed: u32 = Self::GAME_UE5_3 + 7;
    pub const GAME_UE5_4: u32 = Self::GAME_UE5_BASE + (4 << 16);
    pub const GAME_FunkoFusion: u32 = Self::GAME_UE5_4 + 1;
    pub const GAME_InfinityNikki: u32 = Self::GAME_UE5_4 + 2;
    pub const GAME_NevernessToEverness: u32 = Self::GAME_UE5_4 + 3;
    pub const GAME_Gothic1Remake: u32 = Self::GAME_UE5_4 + 4;
    pub const GAME_SplitFiction: u32 = Self::GAME_UE5_4 + 5;
    pub const GAME_WildAssault: u32 = Self::GAME_UE5_4 + 6;
    pub const GAME_InZOI: u32 = Self::GAME_UE5_4 + 7;
    pub const GAME_TempestRising: u32 = Self::GAME_UE5_4 + 8;
    pub const GAME_UE5_5: u32 = Self::GAME_UE5_BASE + (5 << 16);
    pub const GAME_Brickadia: u32 = Self::GAME_UE5_5 + 1;
    pub const GAME_Splitgate2: u32 = Self::GAME_UE5_5 + 2;
    pub const GAME_DeadzoneRogue: u32 = Self::GAME_UE5_5 + 3;
    pub const GAME_MotoGP25: u32 = Self::GAME_UE5_5 + 4;
    pub const GAME_UE5_6: u32 = Self::GAME_UE5_BASE + (6 << 16);
    pub const GAME_UE5_7: u32 = Self::GAME_UE5_BASE + (7 << 16);

    pub const GAME_UE5_LATEST: EGame = Self::UE5_6;

    pub fn GetVersion(&self) -> FPackageFileVersion {
        let value = *self as u32;
        if *self as u32 >= Self::GAME_UE5_0 {
            return match value {
                v if v < EGame::GAME_UE5_1 => FPackageFileVersion::new(522, 1004),
                v if v < EGame::GAME_UE5_2 => FPackageFileVersion::new(522, 1008),
                EGame::GAME_TheFirstDescendant => FPackageFileVersion::new(522, 1002),
                v if v < EGame::GAME_UE5_4 => FPackageFileVersion::new(522, 1009),
                v if v < EGame::GAME_UE5_5 => FPackageFileVersion::new(522, 1012),
                v if v < EGame::GAME_UE5_6 => FPackageFileVersion::new(522, 1013),
                _ => FPackageFileVersion {
                    file_version_ue4: EUnrealEngineObjectUE4Version::AUTOMATIC_VERSION as i32,
                    file_version_ue5: EUnrealEngineObjectUE5Version::AUTOMATIC_VERSION as i32,
                },
            };
        } else {
            return FPackageFileVersion::create_ue4_version(match value {
                // General UE4 Versions
                v if v < EGame::GAME_UE4_1 => 342,
                v if v < EGame::GAME_UE4_2 => 352,
                v if v < EGame::GAME_UE4_3 => 363,
                v if v < EGame::GAME_UE4_4 => 382,
                v if v < EGame::GAME_UE4_5 => 385,
                v if v < EGame::GAME_UE4_6 => 401,
                v if v < EGame::GAME_UE4_7 => 413,
                v if v < EGame::GAME_UE4_8 => 434,
                v if v < EGame::GAME_UE4_9 => 451,
                v if v < EGame::GAME_UE4_10 => 482,
                v if v < EGame::GAME_UE4_11 => 482,
                v if v < EGame::GAME_UE4_12 => 498,
                v if v < EGame::GAME_UE4_13 => 504,
                v if v < EGame::GAME_UE4_14 => 505,
                v if v < EGame::GAME_UE4_15 => 508,
                v if v < EGame::GAME_UE4_16 => 510,
                v if v < EGame::GAME_UE4_17 => 513,
                v if v < EGame::GAME_UE4_18 => 513,
                v if v < EGame::GAME_UE4_19 => 514,
                v if v < EGame::GAME_UE4_20 => 516,
                v if v < EGame::GAME_UE4_21 => 516,
                v if v < EGame::GAME_UE4_22 => 517,
                v if v < EGame::GAME_UE4_23 => 517,
                v if v < EGame::GAME_UE4_24 => 517,
                v if v < EGame::GAME_UE4_25 => 518,
                v if v < EGame::GAME_UE4_26 => 518,
                v if v < EGame::GAME_UE4_27 => 522,
                _ => EUnrealEngineObjectUE4Version::AUTOMATIC_VERSION as i32,
            });
        }
    }
}
