#[repr(u8)]
#[derive(Debug, Clone)]
pub enum EPropertyType {
    ByteProperty = 0,
    BoolProperty,
    IntProperty,
    FloatProperty,
    ObjectProperty,
    NameProperty,
    DelegateProperty,
    DoubleProperty,
    ArrayProperty,
    StructProperty,
    StrProperty,
    TextProperty,
    InterfaceProperty,
    MulticastDelegateProperty,
    WeakObjectProperty,
    LazyObjectProperty,
    AssetObjectProperty,
    SoftObjectProperty,
    UInt64Property,
    UInt32Property,
    UInt16Property,
    Int64Property,
    Int16Property,
    Int8Property,
    MapProperty,
    SetProperty,
    EnumProperty,
    FieldPathProperty,
    OptionalProperty,
    Utf8StrProperty,
    AnsiStrProperty,

    Unknown = 0xFF,
}

impl EPropertyType {
    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => EPropertyType::ByteProperty,
            1 => EPropertyType::BoolProperty,
            2 => EPropertyType::IntProperty,
            3 => EPropertyType::FloatProperty,
            4 => EPropertyType::ObjectProperty,
            5 => EPropertyType::NameProperty,
            6 => EPropertyType::DelegateProperty,
            7 => EPropertyType::DoubleProperty,
            8 => EPropertyType::ArrayProperty,
            9 => EPropertyType::StructProperty,
            10 => EPropertyType::StrProperty,
            11 => EPropertyType::TextProperty,
            12 => EPropertyType::InterfaceProperty,
            13 => EPropertyType::MulticastDelegateProperty,
            14 => EPropertyType::WeakObjectProperty,
            15 => EPropertyType::LazyObjectProperty,
            16 => EPropertyType::AssetObjectProperty,
            17 => EPropertyType::SoftObjectProperty,
            18 => EPropertyType::UInt64Property,
            19 => EPropertyType::UInt32Property,
            20 => EPropertyType::UInt16Property,
            21 => EPropertyType::Int64Property,
            22 => EPropertyType::Int16Property,
            23 => EPropertyType::Int8Property,
            24 => EPropertyType::MapProperty,
            25 => EPropertyType::SetProperty,
            26 => EPropertyType::EnumProperty,
            27 => EPropertyType::FieldPathProperty,
            28 => EPropertyType::OptionalProperty,
            29 => EPropertyType::Utf8StrProperty,
            30 => EPropertyType::AnsiStrProperty,
            _ => EPropertyType::Unknown,
        }
    }
}
